from maze import *

activity = MazeActivity()
activity.always_draw = False
activity.draw()
activity.move()
activity.turn('r')
activity.move(2)
activity.turn('l')
activity.move(2)
activity.turn('r')
activity.move(2)
activity.turn('l')
activity.move(4)
activity.turn('r')
activity.move(2)
activity.turn('l')
activity.move(4)
activity.turn('r')
activity.move(4)
activity.turn('l')
activity.move()

activity = MazeActivity()
activity.always_draw = False
activity.draw()
activity.move(5)
activity.turn('r')
activity.move(2)
activity.turn('l')
activity.move(4)
activity.turn('l')
activity.move(2)
activity.turn('r')
activity.move(2)
activity.turn('r')
activity.move(10)
activity.turn('l')
activity.move()
